### PR TITLE
Added sass, fonts and mixins

### PR DESCRIPTION
**Pull request by sabafarheen**
Please review

### CODE REVIEW

**Review by vibrentcarey — CHANGES_REQUESTED** [review]
Hi Saba, the mixins and fonts look good to me, I am only seeing 3 colors in the variables file are we missing some? https://www.figma.com/file/oRk4LqCj1wYYEtfqZwzdDX/InStock-Mockups?node-id=1196%3A747

**Comment by sabafarheen** [comment]
Okay I will add all the rest. Thanks

**Review by vibrentcarey — APPROVED** [review]
Thank you!

**Comment by miriamnaki** [comment]
LGTM

**Pull request merged**
