### PR TITLE
Back End Set up

### PR DESCRIPTION
**Pull request by miriamnaki**
Set up back end
Add end points for get, post, edit and delete warehouses and inventories

### CODE REVIEW

**Comment by sabafarheen** [comment]
Thank you Miriam for doing an excellent job. Code looks good to me. Hope it is working correctly. I was looking for "axios" and "react-router-dom" in package.json which I did not find. Maybe I missed out.

**Review by sabafarheen — CHANGES_REQUESTED** [review]
Can you please install axios and react-router-dom if not done. Thanks ( I was asked to write comment here)

**Comment by miriamnaki** [comment]
Hi Saba! I think axios and react-router-dom should be installed at the front end in the client folder. This ticket asked to set up the back end and install the required dependencies for the back end.

**Review by sabafarheen — APPROVED** [review]

**Review by vibrentcarey — APPROVED** [review]
Everything looks good, ready to merge to develop!

**Pull request merged**
