### PR TITLE
O21 cs 39

### PR DESCRIPTION
**Pull request by sabafarheen**
Please review this too

### CODE REVIEW

**Review by vibrentcarey — COMMENTED** [review]
Some of the repeated styles could be exported to a global class and then inherited by in stock and out of stock. Not a mandatory change right now so looks good to me!

**Review by veranika-karpava — COMMENTED** [review]
Saba, great job! 
1) I'm not sure, but I think that font-family in front-face will be 'Titillium Web' and not needed space between format and parenthesis (format("truetype"));
2) in out of stock&in stock I saw some name of color(background-colour:#bdc5d5), but not variable. May it will be better change?

**Comment by sabafarheen** [comment]
Thank you Veronica for pointing me about variable name which I missed out. The other changes does not impact much and it has already been merged so I am not going back. Please review the first change.

**Comment by sabafarheen** [comment]
Thank you Brent. I was trying to do global class stuff but it started breaking out so I am leaving it as it is so that I can work in the next ticket. Thanks anyways.

**Review by veranika-karpava — COMMENTED** [review]
Hey Saba, could you delete space between format and () in font-face Titillium Web Regular because it couldn't be loaded for using.

**Comment by sabafarheen** [comment]
Hi,
Veranika it now belong to you. Its already merged. So go ahead & do any
modification if you require.

Thanks

**Review by veranika-karpava — APPROVED** [review]
Thanks Saba!

**Pull request merged**
